project:
  type: website
  resources:
   - assets/*


website:
  title: "HTC/HPC for Stock Assessments"
  reader-mode: true
  site-url: "https://moshima-pifsc.github.io/NSASS-HTC-HPC-Computing" 
  repo-url: "https://github.com/MOshima-PIFSC/NSASS-HTC-HPC-Computing"
  repo-actions: [source, issue]
  search: true
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/MOshima-PIFSC/NSASS-HTC-HPC-Computing
    contents: 
      - text: "Home"
        file: index.qmd
      - text: "Seminar slides"
        file: assets/web-slides.qmd
      - section: "Support"
        contents:
        - text: "Submit an issue"
          href: https://github.com/MOshima-PIFSC/NSASS-HTC-HPC-Computing-dep/issues/new/choose

format: 
  html:
    toc: true
